</$objtype/mkfile

DIRS=docx xlsx

all:V:	$DIRS

$DIRS:V:
	for (i in $DIRS) @{
		echo mk $i
		cd $i
		mk all
	}

install:V:	installdirs

installdirs:V:
	for (i in $DIRS) @{
		echo mk $i
		cd $i
		mk install
	}

update:V:
	update $UPDATEFLAGS $UPDATE
	for (i in $DIRS) @{
		echo update $i
		cd $i
		mk 'UPDATEFLAGS='$"UPDATEFLAGS update
	}

clean:V:
	for (i in $DIRS) @{
		echo clean $i
		cd $i
		mk clean
	}

nuke:V:
	for (i in $DIRS) @{
		echo nuke $i
		cd $i
		mk nuke
	}
