</$objtype/mkfile

LIB=/$objtype/lib/libxml.a

OFILES=\
	xmlattr.$O\
	xmlelem.$O\
	xmlfind.$O\
	xmlfree.$O\
	xmlparse.$O\
	xmlprint.$O\
	xmlnew.$O\
	xmllook.$O\
	xmlvalue.$O\
	heap.$O\

HFILES=\
	/sys/include/xml.h

CLEANFILES=doc.ps $O.doc

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/386/%}

</sys/src/cmd/mksyslib

$O.doc: doc.$O
	$LD -o $target $prereq

doc.ps: 8.doc 
	8.doc | dot '-Grotate=90' '-Gsize=10,8' -Tps > doc.ps
